// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkkCWqShkWHIXsWIvaK-59jPWYcHeofg',
    appId: '1:361220955299:android:9ca6f4999fd71133b57316',
    messagingSenderId: '361220955299',
    projectId: 'wechat-5d8bd',
    storageBucket: 'wechat-5d8bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPA92in1DLaZM1M79Hj4393KorCt8vB5o',
    appId: '1:361220955299:ios:3fb3e8eb89b74c32b57316',
    messagingSenderId: '361220955299',
    projectId: 'wechat-5d8bd',
    storageBucket: 'wechat-5d8bd.appspot.com',
    androidClientId: '361220955299-9o04p9ogv89behgtgog48qs0k5a5l10f.apps.googleusercontent.com',
    iosClientId: '361220955299-ugv4kf7tr16p03shmskjkpsmlt668hi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
